# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eefb31421284643605d288c9e3dec56f02dce81eb53b9d7156a84d6a9e087c961ce106870efbb01b6620d7578c36e2aca27a7e10fed46513bc8b5ab5081391fe

test:
  secret_key_base: 719430b96a55ab4d3c0cfc1048de9fa8de235f75a7fe952575ba4dbbfa4ed1408b02d690eca36914bc898866329bd1debb102ad8fe4bf2b8f582f5e576f69f0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
